### ISSUE TITLE
Responsividad - Seccion nosotros

### ISSUE THREAD

**Issue by maxpipoka** [violebu1/proyecto1react#6]
En esta seccion en la version movil se muestran bien los contenidos. El texpo podría ser un poco mas grande y separarlo en parrrafos distintos para darle mas estructura y que no parezca un bloque.
[https://prnt.sc/3zWXeZGiWWf_](https://prnt.sc/3zWXeZGiWWf_)

Aplica lo mismo para la version desktop de la seccion
[https://prnt.sc/EK7VoukDgvaV](https://prnt.sc/EK7VoukDgvaV)

En el ejemplo le aplique un font-size de 1.5em al 'p' y quedo asi
[https://prnt.sc/pV2ozH7SYeox](https://prnt.sc/pV2ozH7SYeox)

**Comment by violebu1** [comment]
Listo! Perdon q hice commit antes de ver todos los issues, no sabia que estaba corrigiendo justo :D

**Comment by maxpipoka** [comment]
Al hacer la actualización del repo en mi compu se refleja el cambio en el archi CSS pero se esta pisando la regla al 'p' por otro archivo se ve. Habria que aplicarle una clase particular a ese parrafo o parrafos xq siguen siendo todo uno solo, y luego en el css de ese componente agregar la regla para esa clase.
Se evitan los problemas de solapado de css mediante los css modules.
Te lo doy por solucionado.
